image: node:14-alpine

pages:
  stage: deploy
  before_script:
    - apk add yarn
    - yarn
  script:
    - yarn sitemap
    - mv docs public
  only:
    - release
  artifacts:
    paths:
      - public
