image: node:alpine

stages:
  - deploy

deploy:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apk add --update openssh )'
    - apk add --update bash
    - apk add --update git
    - eval $(ssh-agent -s)
    - echo "$CI_SSH_DEPLOY_SECRET" | ssh-add -
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - 'ssh-keyscan -H git.amazingcat.net >> ~/.ssh/known_hosts'

  script:
    - npm i -g pm2
    - npm run sitemap
    - pm2 deploy production

  only:
    - release
