pages:
  stage: deploy
  image: node:14-alpine
  environment:
    name: production
    url: https://docs.cattr.app
  only:
    - tags
  before_script:
    - apk add yarn
    - yarn
  script:
    - yarn sitemap
    - mv docs public
    - mv _redirects ./public
  artifacts:
    paths:
      - public
